project:
  type: website
  output-dir: docs

website:
  title: "Preparatory R Course 2026"
  sidebar:
    style: docked
    contents:
      - index.qmd
      - 01_Intro.qmd
      - 02_Vectors.qmd
      - 03_Dataframes.qmd
      - 04_ReadingData.qmd
      - 05_PlottingPackages.qmd
      - 06_Packages.qmd
      - 07_DataWrangling.qmd
      - 08_ConditionalsIteration.qmd
      - 09_Functions.qmd
      - 10_FinalProject.qmd

format:
  html:
    theme: cosmo
    toc: true